"""Skills taxonomy.

Format of each entry:  "Canonical name|alias 1|alias 2 @family"
- aliases are alternative spellings found in resumes and job posts
- skills sharing a @family are related: having one gives partial credit for another
  (e.g. PyTorch partially covers a TensorFlow requirement)
"""
from __future__ import annotations

from dataclasses import dataclass

RAW_TAXONOMY: dict[str, list[str]] = {
    "Programming languages": [
        "Python @py",
        "Java @jvm",
        "JavaScript|JS|ECMAScript|ES6 @js",
        "TypeScript|TS @js",
        "C @c",
        "C++|CPP @c",
        "C#|C Sharp|CSharp @dotnet",
        "Go|Golang @systems",
        "Rust @systems",
        "Kotlin @jvm",
        "Scala @jvm",
        "Swift @apple",
        "Objective-C @apple",
        "PHP @php",
        "Ruby @ruby",
        "R|R programming|RStudio @stats",
        "MATLAB @stats",
        "SAS @stats",
        "Perl @scripting",
        "Bash|Shell scripting|shell script|Unix shell @scripting",
        "PowerShell @scripting",
        "VBA|Visual Basic|VB.NET @dotnet",
        "Dart @mobile",
        "Solidity @blockchain",
        "COBOL @mainframe",
        "Assembly|Assembly language @c",
        "Groovy @jvm",
        "Haskell @functional",
    ],
    "Web frontend": [
        "HTML|HTML5 @web",
        "CSS|CSS3 @web",
        "React|React.js|ReactJS @frontend",
        "Angular|AngularJS|Angular.js @frontend",
        "Vue.js|Vue|VueJS @frontend",
        "Next.js|NextJS @frontend",
        "Svelte @frontend",
        "jQuery @frontend",
        "Redux @frontend",
        "Bootstrap @css",
        "Tailwind CSS|Tailwind|TailwindCSS @css",
        "Sass|SCSS @css",
        "Material UI|MUI @css",
        "Webpack|Vite @frontend_build",
        "Responsive design|responsive web design @web",
        "Web accessibility|WCAG|a11y @web",
    ],
    "Backend & APIs": [
        "Node.js|NodeJS|Node @node",
        "Express|Express.js|ExpressJS @node",
        "NestJS @node",
        "Django @py_web",
        "Flask @py_web",
        "FastAPI @py_web",
        "Spring|Spring Boot|Spring MVC|Spring Framework @jvm_web",
        "Hibernate|JPA @jvm_web",
        "ASP.NET|ASP.NET Core|ASP.NET MVC|.NET Core|.NET Framework|.NET|dotnet @dotnet",
        "Entity Framework|EF Core|Entity Framework Core @dotnet",
        "Laravel @php",
        "Symfony @php",
        "Ruby on Rails|Rails @ruby",
        "REST API|RESTful|REST APIs|RESTful API|RESTful services|REST @api",
        "GraphQL @api",
        "gRPC @api",
        "SOAP|SOAP web services @api",
        "Microservices|microservice architecture @architecture",
        "WebSocket|WebSockets|Socket.IO @api",
        "OAuth|OAuth2|JWT|OpenID Connect @auth",
        "JSP|Servlets|J2EE|Java EE|Jakarta EE @jvm_web",
    ],
    "Mobile": [
        "Android|Android SDK|Android development @mobile",
        "iOS|iOS development @apple",
        "React Native @mobile",
        "Flutter @mobile",
        "Xamarin @mobile",
        "SwiftUI @apple",
    ],
    "Data science & ML": [
        "Machine learning|ML @ml",
        "Deep learning @dl",
        "scikit-learn|sklearn|scikit learn @ml_lib",
        "TensorFlow|TF2 @dl_framework",
        "PyTorch|Torch @dl_framework",
        "Keras @dl_framework",
        "XGBoost|LightGBM|CatBoost @ml_lib",
        "pandas @py_data",
        "NumPy @py_data",
        "SciPy @py_data",
        "Matplotlib|Seaborn|Plotly @dataviz",
        "Natural language processing|NLP @nlp",
        "Computer vision|OpenCV @cv",
        "Large language models|LLM|LLMs|GPT|generative AI|GenAI @llm",
        "Retrieval-augmented generation|RAG @llm",
        "LangChain|LlamaIndex @llm",
        "Hugging Face|Transformers|BERT @nlp",
        "Statistics|statistical analysis|statistical modeling @stats",
        "Data analysis|data analytics @analytics",
        "Data mining @analytics",
        "Predictive modeling|predictive analytics @ml",
        "Time series|time-series forecasting|time series analysis @stats",
        "A/B testing|experimentation @stats",
        "Feature engineering @ml",
        "MLOps|MLflow|Kubeflow @mlops",
        "Jupyter|Jupyter Notebook @py_data",
        "Reinforcement learning @ml",
        "Recommender systems|recommendation systems @ml",
    ],
    "Data engineering & BI": [
        "SQL|T-SQL|PL/SQL|SQL queries @sql",
        "ETL|ELT|ETL pipelines @etl",
        "Apache Spark|Spark|PySpark @bigdata",
        "Hadoop|HDFS|MapReduce @bigdata",
        "Hive|HiveQL|Pig @bigdata",
        "Kafka|Apache Kafka @streaming",
        "Airflow|Apache Airflow @orchestration",
        "dbt @etl",
        "Informatica|Informatica PowerCenter @etl",
        "SSIS|SQL Server Integration Services @etl",
        "Talend @etl",
        "Data warehousing|data warehouse @dwh",
        "Snowflake @dwh",
        "BigQuery @dwh",
        "Redshift|Amazon Redshift @dwh",
        "Databricks @bigdata",
        "Tableau @bi",
        "Power BI|PowerBI @bi",
        "Looker @bi",
        "Qlik|QlikView|Qlik Sense @bi",
        "SSRS|SQL Server Reporting Services @bi",
        "Data modeling|data modelling @dwh",
        "Data visualization|data visualisation @dataviz",
        "Data governance @dwh",
    ],
    "Databases": [
        "MySQL @rdbms",
        "PostgreSQL|Postgres @rdbms",
        "SQL Server|MS SQL|MSSQL|Microsoft SQL Server @rdbms",
        "Oracle|Oracle Database|Oracle DB @rdbms",
        "SQLite @rdbms",
        "MongoDB|Mongo @nosql",
        "Cassandra @nosql",
        "Redis @nosql",
        "Elasticsearch|ELK|Elastic Stack @search",
        "DynamoDB @nosql",
        "Firebase|Firestore @nosql",
        "Neo4j @nosql",
        "Database administration|DBA @rdbms",
        "Database design @rdbms",
        "Stored procedures @sql",
    ],
    "Cloud & DevOps": [
        "AWS|Amazon Web Services|EC2|S3|Lambda @cloud",
        "Microsoft Azure|Azure @cloud",
        "Google Cloud|GCP|Google Cloud Platform @cloud",
        "Docker|containers|containerization @containers",
        "Kubernetes|K8s|EKS|AKS|GKE @containers",
        "Terraform @iac",
        "Ansible @iac",
        "Chef|Puppet @iac",
        "CloudFormation @iac",
        "CI/CD|continuous integration|continuous delivery|continuous deployment @cicd",
        "Jenkins @cicd",
        "GitHub Actions @cicd",
        "GitLab CI|GitLab @cicd",
        "Azure DevOps|VSTS|TFS @cicd",
        "Git|version control @vcs",
        "GitHub|Bitbucket @vcs",
        "SVN|Subversion @vcs",
        "Linux|Unix|Ubuntu|Red Hat|RHEL|CentOS @os",
        "Windows Server @os",
        "Nginx|Apache HTTP Server|Apache Tomcat|Tomcat|IIS @webserver",
        "Prometheus|Grafana @monitoring",
        "Datadog|Splunk|New Relic|Nagios @monitoring",
        "Maven|Gradle|Ant @build",
        "Site reliability engineering|SRE @devops",
        "Serverless @cloud",
        "Infrastructure as code|IaC @iac",
        "VMware|virtualization|Hyper-V @os",
    ],
    "Testing & QA": [
        "Software testing|QA|quality assurance @testing",
        "Manual testing @testing",
        "Test automation|automation testing|automated testing @test_auto",
        "Selenium|Selenium WebDriver @test_auto",
        "Cypress|Playwright @test_auto",
        "JUnit|TestNG @unit_test",
        "pytest|unittest @unit_test",
        "Jest|Mocha|Jasmine @unit_test",
        "Unit testing @unit_test",
        "Integration testing @testing",
        "Regression testing @testing",
        "Performance testing|load testing|JMeter|LoadRunner|Locust @perf_test",
        "API testing|Postman|SoapUI|REST Assured @api_test",
        "Cucumber|BDD|Gherkin @test_auto",
        "Test-driven development|TDD @unit_test",
        "Test planning|test cases|test plan|test scenarios @testing",
        "Defect tracking|bug tracking|Bugzilla @testing",
        "HP ALM|Quality Center|QTP|UFT @test_auto",
        "Mobile testing|Appium @test_auto",
    ],
    "Security & networking": [
        "Cybersecurity|cyber security|information security|InfoSec @security",
        "Network security @security",
        "Penetration testing|pentesting|ethical hacking @security",
        "Vulnerability assessment|vulnerability management @security",
        "Firewalls|firewall @netsec",
        "SIEM|QRadar|ArcSight @security",
        "IDS|IPS|intrusion detection @netsec",
        "Wireshark|Nmap|Metasploit|Burp Suite|Kali Linux @security",
        "ISO 27001|NIST|SOC 2|GDPR|PCI DSS @compliance",
        "Identity and access management|IAM|Active Directory|LDAP @iam",
        "Cryptography|encryption|PKI @security",
        "TCP/IP|DNS|DHCP|HTTP @networking",
        "Routing and switching|routing|switching|BGP|OSPF|VLAN @networking",
        "Cisco|CCNA|CCNP @networking",
        "VPN @netsec",
        "LAN/WAN|LAN|WAN @networking",
        "Network administration|network administrator @networking",
        "Incident response @security",
    ],
    "Blockchain": [
        "Blockchain @blockchain",
        "Ethereum @blockchain",
        "Smart contracts @blockchain",
        "Hyperledger|Hyperledger Fabric @blockchain",
        "Web3|Web3.js|ethers.js @blockchain",
        "Truffle|Hardhat @blockchain",
    ],
    "ERP & enterprise": [
        "SAP @sap",
        "SAP ABAP|ABAP @sap",
        "SAP HANA|HANA @sap",
        "SAP FICO|SAP FI|SAP CO @sap",
        "SAP MM|SAP SD|SAP PP @sap",
        "SAP Fiori|SAPUI5 @sap",
        "Salesforce|SFDC|Apex @crm",
        "Microsoft Dynamics|Dynamics 365|Dynamics GP @erp",
        "Oracle EBS|Oracle E-Business Suite|Oracle Financials @erp",
        "ServiceNow @itsm",
        "ITIL @itsm",
        "SharePoint @office",
        "Mainframe|z/OS|JCL|CICS|DB2 @mainframe",
    ],
    "Design & media": [
        "Adobe Photoshop|Photoshop @design",
        "Adobe Illustrator|Illustrator @design",
        "Adobe InDesign|InDesign @design",
        "Adobe Premiere Pro|Premiere Pro|Final Cut Pro @video",
        "After Effects|Adobe After Effects @video",
        "Figma @ui_design",
        "Sketch|Adobe XD|InVision @ui_design",
        "UI design|user interface design @ui_design",
        "UX design|user experience|UX research|usability testing @ux",
        "Wireframing|prototyping|wireframes @ux",
        "Graphic design @design",
        "Typography @design",
        "Branding|brand identity @marketing",
        "AutoCAD|CAD @cad",
        "SolidWorks @cad",
        "CATIA @cad",
        "Revit|BIM @cad",
        "SketchUp @cad",
        "3ds Max|Maya|Blender|3D modeling @3d",
        "Video editing @video",
        "Photography @design",
        "Unity|Unity3D @gamedev",
        "Unreal Engine @gamedev",
    ],
    "Engineering": [
        "Mechanical design @mech",
        "Finite element analysis|FEA|ANSYS @mech",
        "Thermodynamics|HVAC|heat transfer @mech",
        "GD&T|geometric dimensioning @mech",
        "Manufacturing|lean manufacturing|Six Sigma|Lean Six Sigma|Kaizen @manufacturing",
        "Quality control|quality inspection|ISO 9001 @manufacturing",
        "PLC|SCADA|PLC programming @automation",
        "Electrical design|circuit design|power systems @electrical",
        "Embedded systems|microcontrollers|Arduino|Raspberry Pi @embedded",
        "PCB design|Altium|Eagle @electrical",
        "Structural analysis|structural engineering|STAAD Pro|ETABS @civil",
        "Construction management|site supervision @construction",
        "Surveying|land surveying @civil",
        "Cost estimation|quantity surveying|cost estimating @construction",
        "Project scheduling|Primavera|Primavera P6 @pm_tools",
        "Aviation safety|FAA regulations|aircraft maintenance @aviation",
        "Automotive|vehicle diagnostics @automotive",
        "Agronomy|crop management|irrigation @agriculture",
    ],
    "Project & product management": [
        "Project management|PMP @pm",
        "Agile|Agile methodology|Agile/Scrum @agile",
        "Scrum|Scrum Master|sprint planning @agile",
        "Kanban @agile",
        "Jira|Confluence @pm_tools",
        "Microsoft Project|MS Project @pm_tools",
        "Product management|product owner|product roadmap @product",
        "Stakeholder management @pm",
        "Risk management @pm",
        "Budgeting|budget management @finance",
        "Requirements gathering|requirements analysis|business requirements @ba",
        "Business analysis|business analyst @ba",
        "Process improvement|business process improvement|BPM @ba",
        "UML|use cases|user stories @ba",
        "Change management @pm",
        "PRINCE2 @pm",
        "Waterfall|SDLC @pm",
        "PMO|portfolio management|program management @pm",
    ],
    "Business, finance & office": [
        "Microsoft Excel|Excel|MS Excel|pivot tables|VLOOKUP @office",
        "Microsoft Office|MS Office|Word|PowerPoint|Outlook @office",
        "Google Workspace|Google Sheets|G Suite @office",
        "Accounting|bookkeeping @accounting",
        "General ledger|GL|accounts payable|accounts receivable @accounting",
        "Financial reporting|financial statements @accounting",
        "Financial analysis|financial modeling|financial modelling @finance",
        "GAAP|IFRS @accounting",
        "Auditing|Audit|internal audit|external audit|audit procedures @accounting",
        "Tax preparation|taxation|tax @accounting",
        "QuickBooks|Xero|Sage @accounting",
        "Payroll|ADP @hr",
        "Forecasting and budgeting|FP&A @finance",
        "Banking|retail banking|loans|credit analysis @banking",
        "Investment|investment analysis|equity research|asset management @finance",
        "Anti-money laundering|AML|KYC @banking",
        "Risk assessment @finance",
        "Procurement|purchasing|sourcing|vendor management @supply_chain",
        "Supply chain|logistics|inventory management|warehouse management @supply_chain",
        "Operations management|operations @operations",
        "Data entry @admin",
        "Customer service|customer support|client service @customer",
        "CRM|HubSpot|Zoho @crm",
        "Call center|BPO|inbound calls|outbound calls @customer",
    ],
    "Sales, marketing & HR": [
        "Sales|B2B sales|B2C sales|business development @sales",
        "Lead generation|prospecting|cold calling @sales",
        "Account management|key account management @sales",
        "Negotiation @sales",
        "Digital marketing|online marketing @marketing",
        "SEO|search engine optimization @marketing",
        "SEM|Google Ads|PPC|AdWords @marketing",
        "Social media marketing|social media|SMM @marketing",
        "Content marketing|content creation|copywriting @content",
        "Email marketing|Mailchimp @marketing",
        "Google Analytics|GA4 @analytics",
        "Market research @marketing",
        "Public relations|PR|media relations|press releases @pr",
        "Event management|event planning @events",
        "Recruitment|recruiting|talent acquisition|sourcing candidates @hr",
        "Onboarding|employee onboarding @hr",
        "Employee relations @hr",
        "Performance management @hr",
        "Compensation and benefits|benefits administration @hr",
        "HRIS|Workday|SuccessFactors @hr",
        "Training and development|learning and development|L&D @hr",
        "Labor law|employment law @hr",
        "Merchandising|visual merchandising @retail",
        "Retail|store management @retail",
        "Fashion design|apparel design|textiles @apparel",
        "Food safety|HACCP|ServSafe @food",
        "Culinary|cooking|menu planning @food",
        "Hospitality|guest services @hospitality",
    ],
    "Legal, education & health": [
        "Legal research|legal writing @legal",
        "Litigation|civil litigation @legal",
        "Contract law|contract drafting|contracts @legal",
        "Corporate law|compliance @legal",
        "Teaching|instruction|lesson planning|curriculum development @education",
        "Classroom management @education",
        "E-learning|LMS|Moodle|instructional design @education",
        "Tutoring|mentoring @education",
        "Personal training|fitness training|strength and conditioning @fitness",
        "Nutrition|dietetics|meal planning @fitness",
        "CPR|First Aid|AED @health",
        "Patient care|healthcare @health",
    ],
    "Soft skills": [
        "Leadership|team leadership|team lead @soft",
        "Communication|communication skills @soft",
        "Teamwork|collaboration @soft",
        "Problem solving|problem-solving @soft",
        "Time management @soft",
        "Mentoring and coaching|coaching @soft",
        "Presentation skills|public speaking @soft",
        "Critical thinking @soft",
    ],
}


@dataclass(frozen=True)
class Skill:
    name: str
    category: str
    family: str
    aliases: tuple[str, ...]


def _parse() -> dict[str, Skill]:
    skills: dict[str, Skill] = {}
    seen_aliases: dict[str, str] = {}
    for category, entries in RAW_TAXONOMY.items():
        for entry in entries:
            names, _, family = entry.partition("@")
            parts = [p.strip() for p in names.split("|") if p.strip()]
            name = parts[0]
            if name in skills:
                raise ValueError(f"Duplicate skill in taxonomy: {name}")
            for alias in parts:
                if alias.lower() in seen_aliases:
                    raise ValueError(f"Alias '{alias}' used by both {seen_aliases[alias.lower()]} and {name}")
                seen_aliases[alias.lower()] = name
            skills[name] = Skill(name, category, family.strip() or name.lower(), tuple(parts))
    return skills


SKILLS: dict[str, Skill] = _parse()

# Very short / ambiguous aliases that only count when written exactly (case-sensitive)
CASE_SENSITIVE_ALIASES = {
    "C", "R", "Go", "JS", "TS", "GL", "PR", "ML", "QA", "BI", "IAM", "SAS", "DNS", "IDS",
    "IPS", "LAN", "WAN", "SEM", "PPC", "SRE", "IaC", "AWS", "GCP", "NLP", "LLM", "RAG",
    "BDD", "TDD", "SQL", "PMO", "CAD", "BIM", "FEA", "PLC", "BPO", "CRM", "SEO", "SMM",
    "AML", "KYC", "ADP", "HRIS", "L&D", "BPM", "UML", "DBA", "ELK", "EKS", "AKS", "GKE",
    "S3", "EC2", "PKI", "VPN", "REST", "UX", "UI", "MUI", "TF2", "GA4", "AED", "CPR", "LMS",
    "SDLC", "ITIL", "SAP", "ABAP", "HANA", "Node", "Torch", "Rails", "Vue", "Spark", "Word",
    "Sage", "Zoho", "Maya", "Chef", "Ant", "Mongo", "Unity", "Tax", "Audit", "Loans",
    "Retail", "Sales", "Operations", "Forecasting", "Statistics", "Negotiation",
    "Teaching", "Recruiting", "Recruitment", "Payroll", "Banking", "Investment", "Procurement",
    "Logistics", "Leadership", "Communication", "Teamwork", "Collaboration", "Hospitality",
    "Merchandising", "Nutrition", "Litigation", "Typography", "Photography", "Branding",
    "Manufacturing", "Automotive", "Surveying", "Accounting", "Bookkeeping", "Tutoring",
    "Mentoring", "Social media", "Cooking", "Culinary", "Onboarding", "Budgeting", "Sourcing", "Purchasing", "Contracts", "Compliance",
    "Routing", "Switching", "Instruction", "Cooking", "Coaching", "Healthcare", "Unix",
}
